baseURL = "https://malocarecords.com"
languageCode = "en-US"
title = "MALOCA Records | Record label from Brussels"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    description = "Worldwide community and electronic music record label based in Brussels. More info soon!"
    author = "Le Motel"