baseURL = "https://malocarecords.com"
languageCode = "en-US"
title = "MALOCA Records"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    description = "Record label from Belgium"
    author = "Studio Colibri"