languageCode = "en-US"
title = "Maloca Records | Record label from Brussels run by Le Motel"
disableKinds = ["taxonomy", "taxonomyTerm"]
cloudinary_url = "https://res.cloudinary.com/dbftnu0ia/image/upload"

[params]
    description = "Maloca is a Worldwide community and electronic music record label based in Brussels. More info soon!"
    author = "Le Motel"
	cloudinary_url = "https://res.cloudinary.com/dbftnu0ia/image/upload"

	
	